# Generated by Django 4.1.5 on 2023-01-20 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='name',
            field=models.CharField(default='sambhav', max_length=50),
            preserve_default=False,
        ),
    ]
