# Generated by Django 4.1.5 on 2023-01-20 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_articles_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='address',
            field=models.CharField(max_length=50),
        ),
    ]
