# Generated by Django 4.1.5 on 2023-01-20 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_alter_articles_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='address',
            field=models.TextField(),
        ),
    ]
